/**
 * BlufPanel — the most prominent element on the investigation page.
 *
 * ---------------------------------------------------------------------------
 * THE TEXT IS RENDERED VERBATIM.
 * ---------------------------------------------------------------------------
 * The BLUF is generated by the intelligence layer and grounded in structured
 * evidence. This component does not summarise it, regenerate it, reword it,
 * clamp it, or truncate it. It only sets type large enough to be scanned in
 * under five seconds.
 */

export interface BlufPanelProps {
  /** The exact `bluf` string from GET /api/incidents/{id}. */
  bluf: string | null | undefined;
}

export function BlufPanel({ bluf }: BlufPanelProps) {
  const text = typeof bluf === 'string' ? bluf.trim() : '';

  return (
    <section className="bluf" aria-labelledby="bluf-heading">
      <div className="bluf__header">
        <h2 id="bluf-heading" className="bluf__title">
          BLUF
        </h2>
        <span
          className="bluf__expansion"
          title="Bottom Line Up Front — the conclusion first, before the supporting detail."
        >
          Bottom Line Up Front
        </span>
      </div>

      {text ? (
        // Rendered in full. No line clamp, no ellipsis, no max-height.
        <p className="bluf__text">{text}</p>
      ) : (
        <p className="bluf__text bluf__text--absent">
          No BLUF summary was returned for this incident.
        </p>
      )}
    </section>
  );
}
